/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package playground;

public class App {
    public final String getGreeting() {
        return "Hello world.";
    }

    public static void main(final String[] args) {
        System.out.println(new App().getGreeting());
    }
}
